import React, { useEffect, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer, useMap } from 'react-leaflet';
import './App.css';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';

const REFRESH_INTERVAL_MS = 30 * 60 * 1000;
const MAP_CENTER = [20, 0];
const MAP_ZOOM = 2;
const MAP_FOCUS_ZOOM = 4;

function getSeverityColor(reportCount) {
  if (reportCount >= 5) {
    return '#dc2626';
  }

  if (reportCount >= 3) {
    return '#f97316';
  }

  return '#facc15';
}

function getSeverityLabel(reportCount) {
  if (reportCount >= 5) {
    return 'High activity';
  }

  if (reportCount >= 3) {
    return 'Medium activity';
  }

  return 'Low activity';
}

function getSeverityKey(reportCount) {
  if (reportCount >= 5) {
    return 'high';
  }

  if (reportCount >= 3) {
    return 'medium';
  }

  return 'low';
}

function getMarkerClassName(reportCount, isSelected) {
  const severityKey = getSeverityKey(reportCount);
  return [
    'signal-marker',
    `signal-marker--${severityKey}`,
    isSelected ? 'signal-marker--selected' : '',
  ].filter(Boolean).join(' ');
}

function formatPublishedDate(publishedAt) {
  const publishedDate = new Date(publishedAt);

  if (Number.isNaN(publishedDate.getTime())) {
    return 'Date unavailable';
  }

  return publishedDate.toLocaleDateString();
}

function MapViewportController({ selectedMarker }) {
  const map = useMap();

  useEffect(() => {
    if (!selectedMarker) {
      map.flyTo(MAP_CENTER, MAP_ZOOM, {
        animate: true,
        duration: 1,
      });
      return;
    }

    map.flyTo(selectedMarker.coordinates, MAP_FOCUS_ZOOM, {
      animate: true,
      duration: 1.2,
    });
  }, [map, selectedMarker]);

  return null;
}

function buildLocationMarkers(data) {
  const groupedLocations = new Map();

  data
    .filter(item => Array.isArray(item.coordinates) && item.coordinates.length === 2)
    .forEach(item => {
      const [lat, lng] = item.coordinates;
      const locationKey = `${item.location_name || 'unknown'}:${lat}:${lng}`;
      const existingLocation = groupedLocations.get(locationKey);

      if (existingLocation) {
        existingLocation.reportCount += 1;
        existingLocation.reports.push(item);
        return;
      }

      groupedLocations.set(locationKey, {
        id: locationKey,
        coordinates: [lat, lng],
        locationName: item.location_name || 'Unknown location',
        reportCount: 1,
        reports: [item],
      });
    });

  return Array.from(groupedLocations.values())
    .map(location => ({
      ...location,
      reports: [...location.reports].sort((left, right) => new Date(right.published) - new Date(left.published)),
    }))
    .sort((left, right) => right.reportCount - left.reportCount);
}

// Fix marker icons in React Leaflet
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png',
  iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
});

function App() {
  const [markers, setMarkers] = useState([]);
  const [selectedMarkerId, setSelectedMarkerId] = useState('');
  const [isPanelOpen, setIsPanelOpen] = useState(true);
  const [locationFilter, setLocationFilter] = useState('all');
  const [severityFilter, setSeverityFilter] = useState('all');
  const [totalReports, setTotalReports] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState(null);
  const [loadError, setLoadError] = useState('');
  const outbreakDataUrl = `${process.env.PUBLIC_URL}/outbreak.json`;

  useEffect(() => {
    const loadOutbreakData = () => {
      fetch(`${outbreakDataUrl}?t=${Date.now()}`, { cache: 'no-store' })
      .then(response => {
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}`);
        }

        return response.json();
      })
      .then(data => {
        if (!Array.isArray(data)) {
          setMarkers([]);
          setTotalReports(0);
          setLoadError('Invalid data format');
          setIsLoading(false);
          return;
        }

        setTotalReports(data.length);
        setLoadError('');
        setMarkers(buildLocationMarkers(data));
        setLastUpdated(new Date());
        setIsLoading(false);
      })
      .catch(error => {
        console.error('Data loading error:', error);
        setMarkers([]);
        setTotalReports(0);
        setLoadError('Unable to load outbreak data');
        setIsLoading(false);
      });
    };

    // Load the outbreak feed generated by the Python pipeline
    loadOutbreakData();
    const intervalId = window.setInterval(loadOutbreakData, REFRESH_INTERVAL_MS);

    return () => window.clearInterval(intervalId);
  }, [outbreakDataUrl]);

  const filteredMarkers = markers.filter(marker => {
    const matchesLocation = locationFilter === 'all' || marker.locationName === locationFilter;
    const matchesSeverity = severityFilter === 'all' || getSeverityKey(marker.reportCount) === severityFilter;

    return matchesLocation && matchesSeverity;
  });

  useEffect(() => {
    if (!filteredMarkers.length) {
      if (selectedMarkerId) {
        setSelectedMarkerId('');
      }

      return;
    }

    const hasSelectedMarker = filteredMarkers.some(marker => marker.id === selectedMarkerId);

    if (!hasSelectedMarker) {
      setSelectedMarkerId(filteredMarkers[0].id);
    }
  }, [filteredMarkers, selectedMarkerId]);

  const geolocatedReports = markers.reduce((reportCount, marker) => reportCount + marker.reportCount, 0);
  const filteredReportCount = filteredMarkers.reduce((reportCount, marker) => reportCount + marker.reportCount, 0);
  const featuredMarker = filteredMarkers.find(marker => marker.id === selectedMarkerId) || filteredMarkers[0] || null;
  const locationOptions = Array.from(new Set(markers.map(marker => marker.locationName))).sort((left, right) => left.localeCompare(right));

  return (
    <div className="app-shell">
      <div className="top-overlay">
        <div className="brand-card glass-card">
          <div className="brand-eyebrow">Signal-led global tracker</div>
          <h1>HantaWatch</h1>
          <p>Editorial-style outbreak mapping inspired by HantavirusMap, tuned for your live feed.</p>
        </div>

        <div className="status-row">
          <div className="stat-pill glass-card">
            <span className="stat-value">{totalReports}</span>
            <span className="stat-label">reports</span>
          </div>
          <div className="stat-pill glass-card">
            <span className="stat-value">{markers.length}</span>
            <span className="stat-label">clusters</span>
          </div>
          <div className="stat-pill glass-card">
            <span className="stat-value">{geolocatedReports}</span>
            <span className="stat-label">mapped</span>
          </div>
        </div>

        <div className="author-card glass-card">
          <div className="author-name">Valentina Schiavon</div>
          <div className="author-copy">Copyright {new Date().getFullYear()} Valentina Schiavon</div>
          <a href="https://github.com/valentinaschiavon99" target="_blank" rel="noreferrer">
            github.com/valentinaschiavon99
          </a>
          <div className="map-credit">
            <span>Map:</span>
            <a href="https://leafletjs.com" target="_blank" rel="noreferrer">Leaflet</a>
            <span>·</span>
            <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>
            <span>·</span>
            <a href="https://carto.com/attributions" target="_blank" rel="noreferrer">CARTO</a>
          </div>
        </div>
      </div>

      <div className="bottom-overlay">
        <div className="bottom-column">
          <div className="info-overlay glass-card">
            <div className="info-title-row">
              <h2>Signal map</h2>
              {isLoading && <span className="info-badge loading">Loading</span>}
              {!isLoading && !loadError && <span className="info-badge live">Live</span>}
              {loadError && <span className="info-badge error">Error</span>}
            </div>
            <p className="info-copy">Yellow, orange and red signals intensify as more reports cluster around the same geolocated area.</p>
            <div className="info-meta">Auto-refresh every 30 minutes</div>
            {lastUpdated && <div className="info-meta">Last update: {lastUpdated.toLocaleString()}</div>}
            {loadError && <div className="info-error">{loadError}</div>}
          </div>

          <div className="legend-overlay glass-card">
            <div className="legend-title">Map intensity</div>
            <div className="legend-item"><span className="legend-dot yellow"></span>Yellow: 1-2 reports</div>
            <div className="legend-item"><span className="legend-dot orange"></span>Orange: 3-4 reports</div>
            <div className="legend-item"><span className="legend-dot red"></span>Red: 5+ reports</div>
          </div>
        </div>

        {isPanelOpen ? (
          <aside className="side-panel glass-card">
            <div className="panel-header">
              <div>
                <div className="featured-eyebrow">Outbreak panel</div>
                <h2 className="panel-title">List and detail</h2>
              </div>
              <div className="panel-header-actions">
                <div className="panel-summary">{filteredMarkers.length} shown</div>
                <button
                  type="button"
                  className="panel-close-button"
                  aria-label="Close outbreak panel"
                  onClick={() => setIsPanelOpen(false)}
                >
                  ×
                </button>
              </div>
            </div>

            <div className="filter-grid">
              <label className="filter-field">
                <span>Country / region</span>
                <select value={locationFilter} onChange={event => setLocationFilter(event.target.value)}>
                  <option value="all">All</option>
                  {locationOptions.map(location => (
                    <option key={location} value={location}>{location}</option>
                  ))}
                </select>
              </label>

              <label className="filter-field">
                <span>Severity</span>
                <select value={severityFilter} onChange={event => setSeverityFilter(event.target.value)}>
                  <option value="all">All</option>
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                </select>
              </label>
            </div>

            <div className="panel-meta-row">
              <span>{filteredReportCount} mapped reports in view</span>
              {(locationFilter !== 'all' || severityFilter !== 'all') && (
                <button
                  type="button"
                  className="text-reset-button"
                  onClick={() => {
                    setLocationFilter('all');
                    setSeverityFilter('all');
                  }}
                >
                  Reset filters
                </button>
              )}
            </div>

            <div className="side-panel-body">
              <div className="outbreak-list">
                {filteredMarkers.length ? filteredMarkers.map(cluster => (
                  <button
                    key={cluster.id}
                    type="button"
                    className={`outbreak-item${cluster.id === selectedMarkerId ? ' is-selected' : ''}`}
                    onClick={() => setSelectedMarkerId(cluster.id)}
                  >
                    <div className="outbreak-item__top">
                      <span className="outbreak-item__name">{cluster.locationName}</span>
                      <span className={`severity-pill severity-pill--${getSeverityKey(cluster.reportCount)}`}>
                        {getSeverityLabel(cluster.reportCount)}
                      </span>
                    </div>
                    <div className="outbreak-item__meta">
                      <span>{cluster.reportCount} reports</span>
                      <span>{cluster.reports[0].source}</span>
                    </div>
                  </button>
                )) : (
                  <div className="empty-panel-state">
                    <strong>No outbreaks found.</strong>
                    <span>Try widening the country or severity filters.</span>
                  </div>
                )}
              </div>

              <div className="detail-panel">
                {featuredMarker ? (
                  <>
                    <div className="featured-header">
                      <div>
                        <div className="featured-eyebrow">Selected cluster</div>
                        <h3 className="featured-title">{featuredMarker.locationName}</h3>
                      </div>
                      <span className={`severity-pill severity-pill--${getSeverityKey(featuredMarker.reportCount)}`}>
                        {getSeverityLabel(featuredMarker.reportCount)}
                      </span>
                    </div>

                    <p className="featured-story">{featuredMarker.reports[0].title}</p>

                    <div className="featured-stats">
                      <div>
                        <strong>{featuredMarker.reportCount}</strong>
                        <span>clustered reports</span>
                      </div>
                      <div>
                        <strong>{featuredMarker.locationName}</strong>
                        <span>active focus</span>
                      </div>
                    </div>

                    <div className="featured-actions">
                      <a
                        className="action-button action-button--primary"
                        href={featuredMarker.reports[0].link}
                        target="_blank"
                        rel="noreferrer"
                      >
                        Open latest report
                      </a>
                    </div>

                    <div className="detail-report-list">
                      {featuredMarker.reports.map((report, index) => (
                        <a
                          key={`${report.link}-${index}`}
                          className="detail-report-link"
                          href={report.link}
                          target="_blank"
                          rel="noreferrer"
                        >
                          <span className="detail-report-source">{report.source}</span>
                          <span className="detail-report-title">{report.title}</span>
                          <span className="detail-report-date">{formatPublishedDate(report.published)}</span>
                        </a>
                      ))}
                    </div>
                  </>
                ) : (
                  <div className="empty-panel-state detail-empty-state">
                    <strong>No active cluster</strong>
                    <span>Select a different filter combination or clear the filters.</span>
                  </div>
                )}
              </div>
            </div>
          </aside>
        ) : (
          <div className="panel-toggle-wrap">
            <button
              type="button"
              className="panel-toggle-button glass-card"
              onClick={() => setIsPanelOpen(true)}
            >
              Open outbreak panel
            </button>
          </div>
        )}
      </div>

      <MapContainer
        center={MAP_CENTER}
        zoom={MAP_ZOOM}
        style={{ height: '100%', width: '100%' }}
        zoomControl={false}
        attributionControl={false}
        closePopupOnClick={true}
        className="signal-map"
      >
        <MapViewportController selectedMarker={featuredMarker} />
        <TileLayer
          url="https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png"
        />
        {filteredMarkers.map((m, i) => (
          <CircleMarker
            key={i}
            center={m.coordinates}
            radius={Math.min(26, 8 + m.reportCount * 2.4)}
            pathOptions={{
              className: getMarkerClassName(m.reportCount, m.id === selectedMarkerId),
              color: m.id === selectedMarkerId ? '#ffffff' : getSeverityColor(m.reportCount),
              fillColor: getSeverityColor(m.reportCount),
              fillOpacity: m.id === selectedMarkerId ? 0.92 : 0.78,
              weight: m.id === selectedMarkerId ? 2.8 : 1.2,
              opacity: 1,
            }}
            eventHandlers={{
              click: () => setSelectedMarkerId(m.id),
            }}
          >
            <Popup closeButton autoClose closeOnEscapeKey keepInView>
              <strong>{m.locationName}</strong><br/>
              Severity: {getSeverityLabel(m.reportCount)}<br/>
              Reports: {m.reportCount}<br/>
              <a href={m.reports[0].link} target="_blank" rel="noreferrer">Read latest report</a>
            </Popup>
          </CircleMarker>
        ))}
      </MapContainer>
    </div>
  );
}

export default App;