import React, { useEffect, useState } from 'react';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';

// Fix marker icons in React Leaflet
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png',
  iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
});

function App() {
  const [markers, setMarkers] = useState([]);
  const [totalReports, setTotalReports] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState('');
  const outbreakDataUrl = `${process.env.PUBLIC_URL}/outbreak.json`;

  useEffect(() => {
    // Load the outbreak feed generated by the Python pipeline
    fetch(outbreakDataUrl)
      .then(response => response.json())
      .then(data => {
        if (!Array.isArray(data)) {
          setMarkers([]);
          setTotalReports(0);
          setLoadError('Invalid data format');
          setIsLoading(false);
          return;
        }

        // Keep only reports that include coordinates
        const geocoded = data.filter(item => item.coordinates);
        setTotalReports(data.length);
        setLoadError('');
        setMarkers(geocoded);
        setIsLoading(false);
      })
      .catch(error => {
        console.error('Data loading error:', error);
        setMarkers([]);
        setTotalReports(0);
        setLoadError('Unable to load outbreak data');
        setIsLoading(false);
      });
  }, [outbreakDataUrl]);

  return (
    <div style={{ height: '100vh', width: '100%' }}>
      <div style={{ 
        position: 'absolute', top: 10, left: 50, zIndex: 1000, 
        background: 'white', padding: '10px', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.3)' 
      }}>
        <h2 style={{ margin: 0, color: '#b91c1c' }}>⚠️ HantaWatch Live</h2>
        {isLoading && <div style={{ marginTop: '4px', color: '#92400e' }}>Loading outbreak data...</div>}
        <small style={{ display: 'block' }}>Total reports: {totalReports}</small>
        <small>Geolocated points: {markers.length}</small>
        {loadError && <div style={{ marginTop: '4px', color: '#991b1b' }}>{loadError}</div>}
      </div>

      <MapContainer center={[20, 0]} zoom={2} style={{ height: '100%', width: '100%' }}>
        <TileLayer
          url="https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png"
          attribution='&copy; OpenStreetMap contributors &copy; CARTO'
        />
        {markers.map((m, i) => (
          <Marker key={i} position={m.coordinates}>
            <Popup>
              <strong>{m.title}</strong><br/>
              <a href={m.link} target="_blank" rel="noreferrer">Read report</a>
            </Popup>
          </Marker>
        ))}
      </MapContainer>
    </div>
  );
}

export default App;