import React, { useEffect, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import './App.css';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';

const REFRESH_INTERVAL_MS = 30 * 60 * 1000;
const MAP_CENTER = [20, 0];
const MAP_ZOOM = 2;

function getSeverityColor(reportCount) {
  if (reportCount >= 5) {
    return '#dc2626';
  }

  if (reportCount >= 3) {
    return '#f97316';
  }

  return '#facc15';
}

function getSeverityLabel(reportCount) {
  if (reportCount >= 5) {
    return 'High activity';
  }

  if (reportCount >= 3) {
    return 'Medium activity';
  }

  return 'Low activity';
}

function buildLocationMarkers(data) {
  const groupedLocations = new Map();

  data
    .filter(item => Array.isArray(item.coordinates) && item.coordinates.length === 2)
    .forEach(item => {
      const [lat, lng] = item.coordinates;
      const locationKey = `${item.location_name || 'unknown'}:${lat}:${lng}`;
      const existingLocation = groupedLocations.get(locationKey);

      if (existingLocation) {
        existingLocation.reportCount += 1;
        existingLocation.reports.push(item);
        return;
      }

      groupedLocations.set(locationKey, {
        coordinates: [lat, lng],
        locationName: item.location_name || 'Unknown location',
        reportCount: 1,
        reports: [item],
      });
    });

  return Array.from(groupedLocations.values()).sort((left, right) => right.reportCount - left.reportCount);
}

// Fix marker icons in React Leaflet
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png',
  iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
});

function App() {
  const [markers, setMarkers] = useState([]);
  const [totalReports, setTotalReports] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState(null);
  const [loadError, setLoadError] = useState('');
  const outbreakDataUrl = `${process.env.PUBLIC_URL}/outbreak.json`;

  useEffect(() => {
    const loadOutbreakData = () => {
      fetch(`${outbreakDataUrl}?t=${Date.now()}`, { cache: 'no-store' })
      .then(response => {
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}`);
        }

        return response.json();
      })
      .then(data => {
        if (!Array.isArray(data)) {
          setMarkers([]);
          setTotalReports(0);
          setLoadError('Invalid data format');
          setIsLoading(false);
          return;
        }

        setTotalReports(data.length);
        setLoadError('');
        setMarkers(buildLocationMarkers(data));
        setLastUpdated(new Date());
        setIsLoading(false);
      })
      .catch(error => {
        console.error('Data loading error:', error);
        setMarkers([]);
        setTotalReports(0);
        setLoadError('Unable to load outbreak data');
        setIsLoading(false);
      });
    };

    // Load the outbreak feed generated by the Python pipeline
    loadOutbreakData();
    const intervalId = window.setInterval(loadOutbreakData, REFRESH_INTERVAL_MS);

    return () => window.clearInterval(intervalId);
  }, [outbreakDataUrl]);

  return (
    <div className="app-shell">
      <div className="top-overlay">
        <div className="brand-card glass-card">
          <div className="brand-eyebrow">Live global tracker</div>
          <h1>HantaWatch</h1>
          <p>Minimal outbreak map with clustered activity signals.</p>
        </div>

        <div className="status-row">
          <div className="stat-pill glass-card">
            <span className="stat-value">{totalReports}</span>
            <span className="stat-label">reports</span>
          </div>
          <div className="stat-pill glass-card">
            <span className="stat-value">{markers.length}</span>
            <span className="stat-label">clusters</span>
          </div>
        </div>

        <div className="author-card glass-card">
          <div className="author-name">Valentina Schiavon</div>
          <div className="author-copy">Copyright {new Date().getFullYear()} Valentina Schiavon</div>
          <a href="https://github.com/valentinaschiavon99" target="_blank" rel="noreferrer">
            github.com/valentinaschiavon99
          </a>
        </div>
      </div>

      <div className="info-overlay glass-card">
        <div className="info-title-row">
          <h2>Signal map</h2>
          {isLoading && <span className="info-badge loading">Loading</span>}
          {!isLoading && !loadError && <span className="info-badge live">Live</span>}
          {loadError && <span className="info-badge error">Error</span>}
        </div>
        <p className="info-copy">Yellow, orange and red indicate denser outbreak reporting around the same geolocated area.</p>
        <div className="info-meta">Auto-refresh every 30 minutes</div>
        {lastUpdated && <div className="info-meta">Last update: {lastUpdated.toLocaleString()}</div>}
        {loadError && <div className="info-error">{loadError}</div>}
      </div>

      <div className="legend-overlay glass-card">
        <div className="legend-title">Map intensity</div>
        <div className="legend-item"><span className="legend-dot yellow"></span>Yellow: 1-2 reports</div>
        <div className="legend-item"><span className="legend-dot orange"></span>Orange: 3-4 reports</div>
        <div className="legend-item"><span className="legend-dot red"></span>Red: 5+ reports</div>
      </div>

      <MapContainer center={MAP_CENTER} zoom={MAP_ZOOM} style={{ height: '100%', width: '100%' }} zoomControl={false}>
        <TileLayer
          url="https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png"
          attribution='&copy; OpenStreetMap contributors &copy; CARTO'
        />
        {markers.map((m, i) => (
          <CircleMarker
            key={i}
            center={m.coordinates}
            radius={Math.min(24, 8 + m.reportCount * 2)}
            pathOptions={{
              color: getSeverityColor(m.reportCount),
              fillColor: getSeverityColor(m.reportCount),
              fillOpacity: 0.78,
              weight: 1,
              opacity: 1,
            }}
          >
            <Popup>
              <strong>{m.locationName}</strong><br/>
              Severity: {getSeverityLabel(m.reportCount)}<br/>
              Reports: {m.reportCount}<br/>
              <a href={m.reports[0].link} target="_blank" rel="noreferrer">Read latest report</a>
            </Popup>
          </CircleMarker>
        ))}
      </MapContainer>
    </div>
  );
}

export default App;